config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :derslers, :path=>"dersler"
  root "derslers#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dersler.rb
class Dersler < ApplicationRecord
    has_attached_file :resim, styles: { medium: "800x400>", thumb: "100x100>" }, default_url:
"/images/:style/missing.png"
validates_attachment_content_type :resim, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/derslers_controller.rb
class DerslersController < ApplicationController
  before_action :set_dersler, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :destroy]
  # GET /derslers
  # GET /derslers.json
  def index
    @derslers = Dersler.all
  end

  # GET /derslers/1
  # GET /derslers/1.json
  def show
  end

  # GET /derslers/new
  def new
    @dersler = Dersler.new
  end

  # GET /derslers/1/edit
  def edit
  end

  # POST /derslers
  # POST /derslers.json
  def create
    @dersler = Dersler.new(dersler_params)

    respond_to do |format|
      if @dersler.save
        format.html { redirect_to @dersler, notice: 'Dersler was successfully created.' }
        format.json { render :show, status: :created, location: @dersler }
      else
        format.html { render :new }
        format.json { render json: @dersler.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /derslers/1
  # PATCH/PUT /derslers/1.json
  def update
    respond_to do |format|
      if @dersler.update(dersler_params)
        format.html { redirect_to @dersler, notice: 'Dersler was successfully updated.' }
        format.json { render :show, status: :ok, location: @dersler }
      else
        format.html { render :edit }
        format.json { render json: @dersler.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /derslers/1
  # DELETE /derslers/1.json
  def destroy
    @dersler.destroy
    respond_to do |format|
      format.html { redirect_to derslers_url, notice: 'Dersler was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dersler
      @dersler = Dersler.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dersler_params
      params.require(:dersler).permit(:baslik, :konu, :aciklama,:resim, :tarih)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/derslers_helper.rb
module DerslersHelper
end

app/views/derslers/_form.html.erb
<%= form_with(model: dersler, local: true) do |form| %>
  <% if dersler.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dersler.errors.count, "error") %> prohibited this dersler from being saved:</h2>

      <ul>
      <% dersler.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Başlık %>
    <%= form.text_field :baslik %>
  </div>

  <div class="field">
    <%= form.label :Yazar %>
    <%= form.text_field :konu %>
  </div>

  <div class="field">
    <%= form.label :aciklama %>
    <%= form.text_area :aciklama %>
  </div>
  <div class="field">
  <%= form.label :resim %>
  <%= form.file_field :resim %>
  </div>
  <div class="field">
    <%= form.label :tarih %>
    <%= form.date_select :tarih %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/derslers/edit.html.erb
<h1>Editing Dersler</h1>

<%= render 'form', dersler: @dersler %>

<%= link_to 'Show', @dersler %> |
<%= link_to 'Back', derslers_path %>

app/views/derslers/index.html.erb
<p id="notice"><%= notice %></p>

  <tbody>
    <% @derslers.each do |dersler| %>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="post-preview">
          <a href="post.html">
            <h2 class="post-title">
            <%= dersler.baslik %>
            </h2>
            <h3 class="post-subtitle">
            <%= dersler.aciklama.first(250) %>...
            </h3>
          </a>
          <p class="post-meta">Posted by
             <%= dersler.konu %>
           
            <%= dersler.tarih %>
            </p>
            <button type="button" class="btn btn-light"><%= link_to 'Show', dersler %></button>
         
        </div>
      </div>
      <% end %>
      
    </div>
  
  </div>
  
 
  </tbody>


<br>

app/views/derslers/new.html.erb
<h1>New Dersler</h1>

<%= render 'form', dersler: @dersler %>

<%= link_to 'Back', derslers_path %>

app/views/derslers/show.html.erb
<p id="notice"><%= notice %></p>

<article>
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
     
      <h2 class="section-heading"> <%= @dersler.baslik %></h2>
      <a href="#">
      <%= image_tag @dersler.resim.url(:medium) if @dersler.resim? %>
      </a>
      <p> <%= @dersler.aciklama %></p>

     
      <p>  <%= @dersler.konu %></p>
      <p>  <%= @dersler.tarih %></p>

<button type="button" class="btn btn-light">  <%= link_to 'Edit', edit_dersler_path(@dersler) %> </button>
<button type="button" class="btn btn-light">  <%= link_to 'Back', derslers_path %></button>

    </div>
  </div>
</div>
</article>

<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   
    </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
  <div class="container">
    <a class="navbar-brand" href="index.html">Ramazan Samet</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      Menu
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="index.html">Anasayfa</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="about.html">Hakkında</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="post.html">Diğer Yazılar</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="contact.html">İletişim</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<header class="masthead" style="background-image: url(/assets/home-bg.jpg)">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Ramazan Blog</h1>
            <span class="subheading">Keyifli Okumalar</span>
          </div>
        </div>
      </div>
    </div>
  </header>
    <%= yield %>
    <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <%= render 'shared/navbar' %>
          <p class="copyright text-muted">Copyright &copy; Your Website 2019</p>
        </div>
      </div>
    </div>
  </footer>
  </body>
</html>

app/views/shared/_navbar.html.erb
<p class="navbar-text pull-right"> <% if user_signed_in? %>
Logged in as <strong><%= current_user.email %></strong>.
<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
<% else %>
<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %> | <%= link_to "Login", new_user_session_path, :class => 'navbar-link' %>
<% end %> </p>